@port = 8080
@baseUrl = http://localhost:{{port}}/api

### * Get All File Requests
GET {{baseUrl}}/file-requests?status=pending&requestedBy=6823a90f87ce3399471a2013&requestedDocumentType=barangay

### * Get All File Requests
GET {{baseUrl}}/file-requests?status=pending&requestedDocumentType=barangay-clearance

### * Get File Request by barangay ID
GET {{baseUrl}}/file-requests?barangayId=681f5663bc1cafa5099611e3

### * Get File Reques
GET {{baseUrl}}/file-requests

### * Get File Request by ID
GET {{baseUrl}}/file-requests/6824d2bce9cdeb1343e94211

### * Create New File Request (you don't have to set status, requestNumber, dateRequested) when creating 
# ! THESE ARE THE DOCUMENT TYPES
# ! "barangay-clearance",
# ! "barangay-indigency",
# ! "certificate-of-residency",
# ! "first-time-job-seeker",

# ! data is an array of attributes (first name, last name, etc) this is dynamic based on document type

# ! NOTE:
# ! documentNumber - auto generated at the backend
# ! issuanceDate - should update automatically when the document was printed
    # ! (use PUT request, then {...data, issuanceDate} then pass it to the file
# ! placeOfIssuance - when the request is being checked by admin
    # ! an input for placeOfIssuance is required before approving the request and printing it

POST {{baseUrl}}/file-requests
Content-Type: application/json

{
  "requestedDocumentType": "barangay-clearance",
  "requestedBy": "6824e07102ab5f580a54f0aa",
  "data": {
    "fullName" : "Jiro Mendador",
    "address" : "112 D. Ko Alam",
    "purok" : "Trese",
    "birthdate" : "2007-02-13T00:00:00.000+00:00",
    "purpose" : "Secret!!!"
  },
  "barangayId": "681f5663bc1cafa5099611e3"
}

### * Create Another File Request
POST {{baseUrl}}/file-requests
Content-Type: application/json

{
  "requestedDocumentType": "barangay-clearance",
  "requestedBy": "68231f10d957bbcd6e2a31ba",
  "data": {
    "fullName" : "",
    "address" : "",
    "purok" : "",
    "birthdate" : "2007-02-13T00:00:00.000+00:00",
    "purpose" : ""
  },
  "barangayId": "681f5663bc1cafa5099611e3"
}

### * Update File Request Info (1 field)
PUT {{baseUrl}}/file-requests/6824fc23c6a6da6d99852a19
Content-Type: application/json

{
  "barangayId": "6824fc23c6a6da6d99852a19"
}

### * Update File Request Info
PUT {{baseUrl}}/file-requests/68292f5c1430b4a6b5cd36d0
Content-Type: application/json

{
  "requestedDocumentType": "barangay-clearance",
  "requestedBy": "68231f10d957bbcd6e2a31ba",
  "data": {
    "fullName" : "HAHA",
    "address" : "HAHA",
    "purok" : "HAHA",
    "birthdate" : "2007-02-13T00:00:00.000+00:00",
    "purpose" : "HAHA"
  },
  "barangayId": "681f5663bc1cafa5099611e3"
}

### * Delete Barangay
DELETE {{baseUrl}}/file-requests/68292fa6e4655577c6320775
